---
title: "Blog"
---

---

**Promoting healthy social media use and sleep in schools**

*17th March 2021*

Social media has changed the way we sleep. At any time, day or night, we can pick up our smartphones and connect with our friends. This is especially relevant for today's teenagers, since adolescence is the time in our lives when peer acceptance and approval are most important. With 24/7 access to online interactions, this desire to engage with friends competes with the need to get enough sleep. This understandably presents a concern for educators and parents, since getting enough sleep is crucial for good physical and mental health and academic performance. Hardly a day goes by without seeing scary headlines about the harm that social media and screens are doing to our young people. This is fueling a worrying but often unhelpful perception of social media as a threat, often talking about "addiction" despite a lack of evidence for using such strong terms. Since 2014, the #sleepyteens research project at the University of Glasgow has been dedicated to looking behind these headlines to examine the evidence on teenage social media and sleep. 

One common worry that has received widespread media coverage is that blue light from phone screens can have an alerting effect on our body clock, keeping teens awake longer. However, the best evidence shows that even spending hours in front of a screen only makes a small difference to how long it takes to fall asleep, compared to reading a paper book. So, if the screen only has a small effect, instead of talking about "screen time", where should we be focusing our attention? It's true: an hour spent on social media (just like any other activity, such as reading or homework) is an hour spent awake. Therefore, teens who spend more time on social media tend to go to bed later and get less sleep because they still need to wake up early for school. Understandably, adults have therefore tried to limit the amount of time that teens spend on social media, especially before bedtime, but this is easier said than done. Researchers have struggled to get teenagers on board with experiments that involve putting down their phone. Therefore, in our research, we have focused on understanding why teens choose to prioritise social media over sleep, to equip schools and parents with knowledge to support their young people to get the balance right. 

Speaking to teens in our research, they told us that they wanted to stay connected to friends, even late at night, to avoid missing out and feeling left out the next day at school. Furthermore, they could feel a sense of obligation to continue conversations past their intended bedtime to avoid offending friends by ending conversations. In a national survey with thousands of pupils, we found that young people who worried more about staying connected and following etiquette in this way tended to use social media for longer after the time they felt they should be asleep, and got less sleep because of this. So rather than focusing on "screen time", educators and parents can think about having an informed dialogue about young people's concerns about disconnecting from social media to sleep. Indeed, speaking to our research partner schools, it became clear that this is something that teachers want to discuss with their pupils, but they are faced with a lack of evidence-based materials, in contrast to a wealth of fearmongering headlines that fuel fear and misinformation. We therefore set out to create new educational materials to support schools to promote balanced social media habits for healthy sleep. 

Researchers have tried to improve adolescent sleep through school lessons before. Generally, these attempts find that teenagers' *knowledge* about sleep improves but their *behaviours* don't change. One important reason for this is motivation: even though teens want more sleep, they face motivational barriers to making changes. Perhaps the number one motivational barrier is disconnecting from social media earlier to allow more time from sleep. The teenage brain is wired to value peer acceptance and approval very strongly, and the risk of being left out is weighed more heavily than other risks, like insufficient sleep. So a promising approach would be for lessons to target underlying concerns about disconnecting from social media at night, aiming to open a dialogue and challenge some of these worries. Through workshops, we have spoken to a range of education stakeholders about just this, exploring what would make lessons successful and what barriers schools might face. We spoke with school leavers, primary and secondary school teachers and senior management, teaching assistants, school nurses, parent-teacher council members and senior Local Education Authority staff. 

One of the potential barriers identified was the generational gap in experiences of social media between teens and adults. Teachers reported feeling out of touch in a rapidly evolving media landscape, struggling to keep up to date with the latest platforms and trends. Adults identified the need to feel able to speak the same language as teens if they were to be seen as credible sources of advice and guidance. Related to this, young people voiced the need to make materials self-relevant for pupils, to avoid feeling alienated by content that does not feel relatable to their experiences. Teachers agreed that keeping lesson materials up to date was important but could be challenging. One promising way to achieve this was identified as having pupils lead lessons and discussions, as young people valued the chance to add their voice rather than feeling "preached to". Teachers similarly recognised the value of encouraging pupils to interact and lead discussions rather than being "lectured". Finally, stakeholders consistently voiced concerns over how to successfully engage parents with the school's efforts, as schools often felt "powerless" without a consistent message at home. 

We used these stakeholder insights, combined with the latest research on adolescent sleep and social media, to develop curriculum materials. A key feature was an online survey the week before lessons started, where pupils reported their typical sleep and social media habits, and how strongly they experienced various worries related to disconnecting at night. This meant that our materials were customised with summary statistics specific to that school, so teachers and pupils could see what was typical for their own school. This empowered teachers with up to date knowledge of their pupils' habits, and provided a relatable evidence base as a starting point for pupil-led discussions. Pupils led data-driven discussions about how much sleep they got, whether they wanted more (typically yes), and how social media could interfere with their planned bedtime. Together, pupils and teachers collaboratively created 'top tips' for balancing social media and sleep, and each pupil chose one tip to try out at home and discuss with their family. Pupils also worked in groups to identify common worries about disconnecting from social media earlier (supported by their school's survey results) and to reframe these in a more constructive way. For example, "I worry that my friend will think I'm rude if I don't answer" might be reframed as "I'll explain that I was sleeping, they'll understand". Finally, pupils finished the last lesson by considering their own strategy for balancing social media and sleep based on what they had discussed. 

Participating pupils praised the opportunity to discuss statistics about sleep and social media habits for their own school, as this allowed them to "see what was normal for other classmates" and "it got everyone thinking about themselves and talking about their own experiences". Seeing statistics about concerns around disconnecting allowed pupils to feel that they are "not the only one" who worries about staying connected and being a good friend online. This feedback highlighted a shift in dynamic away from adults lecturing about an apparently scary health worry, towards young people taking ownership through research to lead discussions and challenge unhelpful preconceptions. This approach promotes autonomy and recognises that teens themselves are the experts in what it is like to balance the competing demands of socialising and sleep as a young person today.

---

 